### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Mugilan-Codes** [aravinthraj98/nodechat#1]
Give Proper Styles.

- Use Reset CSS to reset all the default CSS 
- Put in your stylesheet after

put the link in a head tag like this
```html
<link href='reset.css'>
<link href='style.css'>
```

### Checkout

[Minimal CSS Reset](https://alligator.io/css/minimal-css-reset/)

**Comment by aravinthraj98** [comment]
Ok, I will do it boss!
